GM.Name = "Pickle"
GM.Author = "callousCheddar"
GM.Website = "https://github.com/callouscheddar/pickle"
GM.Email = ""
GM.BaseClass = ""

citizen_models = {}
citizen_models[1] = "models/player/Group01/male_01.mdl"
citizen_models[2] = "models/player/Group01/male_02.mdl"
citizen_models[3] = "models/player/Group01/male_03.mdl"
citizen_models[4] = "models/player/Group01/male_04.mdl"
citizen_models[5] = "models/player/Group01/male_05.mdl"
citizen_models[6] = "models/player/Group01/male_06.mdl"
citizen_models[7] = "models/player/Group01/male_07.mdl"
citizen_models[8] = "models/player/Group01/male_08.mdl"
citizen_models[9] = "models/player/Group01/male_09.mdl"